FROM ruby:3.2.0-bullseye as base

ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y build-essential apt-utils libpq-dev
# RUN apt remove cmdtest -y

# install nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -

# install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update && apt install yarn -y


WORKDIR /docker/app

RUN gem install bundler

COPY Gemfile* ./

RUN bundle install

ADD . /docker/app

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"] ]