version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      RAILS_LOG_TO_STDOUT: true
      RAILS_SERVE_STATIC_FILES: true
    env_file:
      - .env
  app:
    image: frigo_hero:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres: