// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
import "./underscore"
import "./items"
import "./show"
import "./google-autocomplete"
import "./alert"
import "./add_image"
