// Entry point for the build script in your package.json
import "fontawesome-free/js/all"
import "@hotwired/turbo-rails"
import "./controllers"
import "./utils"
import * as bootstrap from "bootstrap"
import "./underscore"
import "./items"
import "./show"
import "./google_autocomplete"
import "./hide_alert_message"
import "./add_image"
